In [1]:
from skimage import io, color
import numpy as np
import matplotlib.pyplot as plt


In [2]:
my_image = io.imread('source/1/1 N NO 4_ch00.tif')
print(my_image)

[[[115 115 115]
  [110 110 110]
  [ 97  97  97]
  ...
  [118 118 118]
  [ 90  90  90]
  [125 125 125]]

 [[ 85  85  85]
  [ 91  91  91]
  [ 96  96  96]
  ...
  [ 97  97  97]
  [115 115 115]
  [106 106 106]]

 [[ 83  83  83]
  [ 97  97  97]
  [ 88  88  88]
  ...
  [128 128 128]
  [106 106 106]
  [106 106 106]]

 ...

 [[119 119 119]
  [129 129 129]
  [115 115 115]
  ...
  [105 105 105]
  [102 102 102]
  [111 111 111]]

 [[120 120 120]
  [102 102 102]
  [111 111 111]
  ...
  [106 106 106]
  [105 105 105]
  [ 97  97  97]]

 [[132 132 132]
  [101 101 101]
  [103 103 103]
  ...
  [114 114 114]
  [ 95  95  95]
  [ 98  98  98]]]
